/* global io */
import { NetworkMap } from './map.js';
import * as dash from './dashboard.js';
import { SimControls } from './simControls.js';
import { initializeLiveAI } from './liveAI.js';
import { createModeStore } from './modeStore.js';

/**
 * Orchestration only:
 *   Socket.IO snapshots -> mode store -> map markers, intersection list,
 *   and (for the selected intersection) dashboard + 3D scene.
 *
 * Map click -> selectIntersection(id) -> everything re-targets the same id.
 *
 * Two data modes that are never mixed (see modeStore.js):
 *   live        real perception data       socket room "live",        REST /api
 *   simulation  generated by the simulator socket room "simulation",  REST /api/simulation
 * Switching mode moves the socket to the other room and redraws everything
 * from that mode's own state. The live view never needs the simulator.
 */

const store = createModeStore();

const state = {
  intersections: [],
  scene: null,
  map: null,
  sim: null,
  socket: null,
  simStatus: null,
};

async function fetchJson(url) {
  const res = await fetch(url, { cache: 'no-store' });
  if (!res.ok) throw new Error(`${url} -> ${res.status}`);
  return res.json();
}

async function createScene() {
  const viewport = document.getElementById('viewport');
  try {
    const { TrafficScene } = await import('./three/scene.js');
    const scene = new TrafficScene(viewport, {
      tagLayer: document.getElementById('vp-tags'),
      compass: document.getElementById('compass'),
    });
    document.getElementById('reset-view').addEventListener('click', () => scene.resetView());
    return scene;
  } catch (err) {
    console.error('3D view failed to start:', err);
    document.getElementById('vp-fallback').hidden = false;
    return null;
  }
}

/** A stopped or paused simulation is shown frozen (no client-side motion or countdown). */
function isFrozen() {
  return store.mode === 'simulation' && (!state.simStatus || state.simStatus.state !== 'running');
}

// ------------------------------------------------------------ snapshots

function stamp(snap) {
  snap._receivedAt = performance.now();
  return snap;
}

function onSnapshot(snap) {
  stamp(snap);
  if (!store.accept(snap)) return; // other mode: kept for later, never drawn now
  if (state.map) state.map.update(snap);
  dash.updateListRow(snap);
  dash.setFeeds(store.all());

  if (snap.intersectionId === store.selectedId) {
    dash.render(snap);
    dash.tickCountdown(snap, isFrozen());
    if (state.scene) state.scene.applyState(snap);
  }
}

/** Socket `init` (after connect / subscribe) and `simulationReset`: all snapshots of one mode. */
function onInit(payload) {
  if (payload.simulation) applySimStatus(payload.simulation);
  const current = store.replaceAll(payload.dataMode || 'live', payload.intersections.map(stamp));
  if (!current) return;
  redrawOverview();
  const selected = store.get();
  if (selected) {
    dash.render(selected);
    if (state.scene) state.scene.applyState(selected);
  }
}

/** Map markers, intersection list and feed pill from the active mode only. */
function redrawOverview() {
  const snaps = store.all();
  dash.resetListRows();
  if (state.map) state.map.setSnapshots(snaps);
  snaps.forEach((s) => dash.updateListRow(s));
  dash.setFeeds(snaps);
}

// ------------------------------------------------------------ selection

async function selectIntersection(id, { pan = false, force = false } = {}) {
  const meta = state.intersections.find((i) => i.id === id);
  if (!meta) return;
  const changed = store.select(id) || force;
  if (window.location.hash !== `#${id}`) window.history.replaceState(null, '', `#${id}`);

  if (state.map) state.map.select(id, { pan });
  if (state.sim) state.sim.refresh();

  // Render immediately from cached socket state, then load the full state
  // (including the event history) from the REST API of the active mode.
  const mode = store.mode;
  const cached = store.get(id);
  dash.setSelected(id, meta.name, cached || meta);
  if (cached) {
    dash.render(cached);
    if (changed && state.scene) state.scene.loadIntersection(cached);
  }

  try {
    const { state: full } = await fetchJson(`${store.apiBase()}/traffic/state/${encodeURIComponent(id)}`);
    // Ignore answers that arrive after the user moved on (other intersection or mode).
    if (store.selectedId !== id || store.mode !== mode) return;
    const events = full.events;
    delete full.events;
    stamp(full);
    if (!store.accept(full)) return;
    dash.render(full);
    dash.tickCountdown(full, isFrozen());
    dash.renderEvents(events);
    if (state.scene) {
      if (!cached && changed) state.scene.loadIntersection(full);
      else state.scene.applyState(full);
    }
  } catch (err) {
    console.warn('Could not load intersection state:', err);
  }
}

// ----------------------------------------------------------- data modes

function applyModeChrome() {
  document.body.dataset.mode = store.mode;
  document.querySelectorAll('.mode-btn').forEach((btn) => {
    const active = btn.dataset.mode === store.mode;
    btn.classList.toggle('active', active);
    btn.setAttribute('aria-selected', String(active));
  });
  dash.setDataMode(store.mode);
  if (state.sim) state.sim.setActive(store.mode === 'simulation');
  if (state.scene) state.scene.setFrozen(isFrozen());
}

async function setMode(mode) {
  if (!store.switchMode(mode)) return;
  applyModeChrome();
  // The server answers with an `init` for the new room.
  if (state.socket && state.socket.connected) state.socket.emit('subscribe', { mode });
  redrawOverview();
  if (store.selectedId) await selectIntersection(store.selectedId, { force: true });
}

function applySimStatus(status) {
  state.simStatus = status;
  if (state.sim) state.sim.apply(status);
  if (state.scene) state.scene.setFrozen(isFrozen());
}

// --------------------------------------------------------------- socket

function connectSocket() {
  dash.setConnection('connecting');
  const socket = io({ transports: ['websocket', 'polling'] });
  state.socket = socket;

  socket.on('connect', () => {
    dash.setConnection('connected', socket.io.engine.transport.name);
    // Every connection starts in the live room; rejoin the simulation room if needed.
    if (store.mode !== 'live') socket.emit('subscribe', { mode: store.mode });
    // Re-sync the selected intersection's event history after a reconnect.
    if (store.selectedId) selectIntersection(store.selectedId);
  });
  socket.on('disconnect', () => dash.setConnection('disconnected'));
  socket.io.on('reconnect_attempt', () => dash.setConnection('connecting'));

  socket.on('init', onInit);
  socket.on('trafficUpdate', onSnapshot);
  socket.on('signalUpdate', onSnapshot);
  socket.on('systemEvent', (evt) => {
    if (store.isCurrentEvent(evt)) dash.appendEvent(evt);
  });
  socket.on('simulationStatus', applySimStatus);
  socket.on('simulationReset', (payload) => {
    onInit(payload);
    if (store.mode === 'simulation' && store.selectedId) selectIntersection(store.selectedId, { force: true });
  });
  socket.on('subscribeError', (err) => console.warn('Socket subscription refused:', err && err.error));
}

// ----------------------------------------------------------------- boot

async function boot() {
  initializeLiveAI();
  dash.initLayout();
  dash.tickClock();
  document.querySelectorAll('.mode-btn').forEach((btn) => {
    btn.addEventListener('click', () => setMode(btn.dataset.mode));
  });

  const scenePromise = createScene();

  let intersections = [];
  for (let attempt = 0; !intersections.length; attempt += 1) {
    try {
      ({ intersections } = await fetchJson('/api/intersections'));
    } catch (err) {
      dash.setConnection('disconnected');
      await new Promise((r) => setTimeout(r, Math.min(5000, 1000 * (attempt + 1))));
    }
  }
  state.intersections = intersections;

  dash.renderIntersectionList(intersections, selectIntersection);
  state.map = new NetworkMap(document.getElementById('map'), intersections, (id) => selectIntersection(id));
  state.scene = await scenePromise;
  state.sim = new SimControls(() => store.selectedId, applySimStatus);
  applyModeChrome();

  const fromHash = decodeURIComponent(window.location.hash.slice(1));
  const initial = intersections.some((i) => i.id === fromHash) ? fromHash : intersections[0].id;

  connectSocket();
  await selectIntersection(initial);

  setInterval(() => {
    dash.tickClock();
    dash.tickCountdown(store.get(), isFrozen());
  }, 200);
}

window.addEventListener('hashchange', () => {
  const id = decodeURIComponent(window.location.hash.slice(1));
  if (id && id !== store.selectedId) selectIntersection(id, { pan: true });
});

boot();
