/* global io */
import { NetworkMap } from './map.js';
import * as dash from './dashboard.js';
import { SimControls } from './simControls.js';
import { initializeLiveAI, updateFromLiveSnapshot } from './liveAI.js';
import { createModeStore } from './modeStore.js';

/**
 * Orchestration only:
 *   Socket.IO snapshots -> mode store -> map markers, intersection list,
 *   and (for the selected intersection) dashboard + Live AI panels + 3D scene.
 *
 * Map click -> selectIntersection(id) -> everything re-targets the same id.
 *
 * Two data modes that are never mixed (see modeStore.js):
 *   live        real perception data: AI service (YOLO on the camera videos)
 *               -> POST /api/traffic -> socket room "live", REST /api
 *   simulation  generated by the simulator (the Simulation tab only)
 *               -> socket room "simulation", REST /api/simulation
 * Each mode has its own intersection list, its own snapshots (the store) and
 * its own socket room; the socket is in exactly one room at a time. Switching
 * mode moves the socket, swaps the map and list, and reloads the 3D scene
 * from that mode's own state, so nothing carries over. Simulated data is
 * always labelled (SIMULATED DATA badge, SIMULATED pills); the Live AI panels
 * never show it.
 *
 * Data state of the selected intersection (dataStateOf):
 *   live        fresh AI data (aiStatus CONNECTED)
 *   waiting     no AI data received yet: nothing is shown as a number
 *   stale       AI data stopped: last values shown, marked stale with their time
 *   offline     the backend connection is lost: shown as reconnecting
 *   simulation  Simulation mode (simulated values, labelled as such)
 * Socket.IO reconnects by itself; every (re)connect brings a fresh `init`.
 */

const store = createModeStore();

const state = {
  lists: { live: [], simulation: [] }, // intersections per data mode
  scene: null,
  map: null,
  sim: null,
  socket: null,
  connected: false,
  simStatus: null,
};

async function fetchJson(url) {
  const res = await fetch(url, { cache: 'no-store' });
  if (!res.ok) throw new Error(`${url} -> ${res.status}`);
  return res.json();
}

async function createScene() {
  const viewport = document.getElementById('viewport');
  try {
    const { TrafficScene } = await import('./three/scene.js');
    const scene = new TrafficScene(viewport, {
      tagLayer: document.getElementById('vp-tags'),
      compass: document.getElementById('compass'),
      statusLayer: document.getElementById('vp-data-state'),
    });
    document.getElementById('reset-view').addEventListener('click', () => scene.resetView());
    return scene;
  } catch (err) {
    console.error('3D view failed to start:', err);
    document.getElementById('vp-data-state').hidden = true;
    document.getElementById('vp-fallback').hidden = false;
    return null;
  }
}

const intersections = () => state.lists[store.mode];

function dataStateOf(snap) {
  if (!state.connected) return 'offline';
  if (store.mode === 'simulation') return 'simulation';
  if (!snap) return 'waiting';
  if (snap.aiStatus === 'CONNECTED') return 'live';
  if (snap.aiStatus === 'STALE') return 'stale';
  return 'waiting';
}

/** A stopped or paused simulation is shown frozen (no client-side motion or countdown). */
function isFrozen() {
  return store.mode === 'simulation' && (!state.simStatus || state.simStatus.state !== 'running');
}

/** Draws the selected intersection everywhere from one snapshot of the active mode. */
function renderSelected({ load = false } = {}) {
  const snap = store.get() || null;
  const dataState = dataStateOf(snap);
  dash.setDataState(dataState, snap);
  // The Live AI panels only ever show live data.
  updateFromLiveSnapshot(store.mode === 'live' ? snap : null, store.mode === 'live' ? dataState : 'simulation');
  if (snap) {
    dash.render(snap, dataState);
    dash.tickCountdown(snap, isFrozen() || !state.connected);
  }
  if (state.scene) {
    state.scene.setDataState(dataState, snap);
    if (store.mode === 'simulation') state.scene.setFrozen(isFrozen());
    if (snap) {
      if (load) state.scene.loadIntersection(snap);
      else state.scene.applyState(snap);
    }
  }
}

// ------------------------------------------------------------ snapshots

function stamp(snap) {
  snap._receivedAt = performance.now();
  return snap;
}

function onSnapshot(snap) {
  stamp(snap);
  if (!store.accept(snap)) return; // other mode: kept for later, never drawn now
  if (state.map) state.map.update(snap);
  dash.updateListRow(snap);
  dash.setFeeds(store.all());
  if (snap.intersectionId === store.selectedId) renderSelected();
}

/** Socket `init` (after connect / subscribe) and `simulationReset`: all snapshots of one mode. */
function onInit(payload) {
  if (payload.simulation) applySimStatus(payload.simulation);
  const current = store.replaceAll(payload.dataMode || 'live', payload.intersections.map(stamp));
  if (!current) return;
  redrawOverview();
  renderSelected({ load: true });
}

/** Map markers, intersection list and feed pill from the active mode only. */
function redrawOverview() {
  const snaps = store.all();
  dash.resetListRows();
  if (state.map) state.map.setSnapshots(snaps);
  snaps.forEach((s) => dash.updateListRow(s));
  dash.setFeeds(snaps);
}

// ------------------------------------------------------------ selection

async function selectIntersection(id, { pan = false, force = false } = {}) {
  const meta = intersections().find((i) => i.id === id);
  if (!meta) return;
  const changed = store.select(id) || force;
  if (window.location.hash !== `#${id}`) window.history.replaceState(null, '', `#${id}`);

  if (state.map) state.map.select(id, { pan });
  if (state.sim) state.sim.refresh();

  // Render immediately from cached socket state, then load the full state
  // (including the event history) from the REST API of the active mode.
  const mode = store.mode;
  const cached = store.get(id);
  dash.setSelected(id, meta.name, cached || meta);
  renderSelected({ load: changed && Boolean(cached) });

  try {
    const { state: full } = await fetchJson(`${store.apiBase()}/traffic/state/${encodeURIComponent(id)}`);
    // Ignore answers that arrive after the user moved on (other intersection or mode).
    if (store.selectedId !== id || store.mode !== mode) return;
    const events = full.events;
    delete full.events;
    dash.renderEvents(events);
    // A newer socket snapshot may already be here; never go back in time.
    const current = store.get(id);
    if (!current || Date.parse(full.serverTime) >= Date.parse(current.serverTime)) {
      stamp(full);
      if (!store.accept(full)) return;
      renderSelected({ load: changed && !cached });
    }
  } catch (err) {
    console.warn('Could not load intersection state:', err);
  }
}

// ----------------------------------------------------------- data modes

function applyModeChrome() {
  document.body.dataset.mode = store.mode;
  document.querySelectorAll('.mode-btn').forEach((btn) => {
    const active = btn.dataset.mode === store.mode;
    btn.classList.toggle('active', active);
    btn.setAttribute('aria-selected', String(active));
  });
  dash.setDataMode(store.mode);
  if (state.sim) state.sim.setActive(store.mode === 'simulation');
  if (state.scene) state.scene.setFrozen(store.mode === 'simulation' && isFrozen());
}

/** The intersection list and map markers of the active mode. */
function showModeIntersections() {
  const list = intersections();
  dash.renderIntersectionList(list, selectIntersection);
  if (state.map && list.length) state.map.setIntersections(list);
}

async function setMode(mode) {
  if (!store.switchMode(mode)) return;
  applyModeChrome();
  // The server answers with an `init` for the new room.
  if (state.socket && state.socket.connected) state.socket.emit('subscribe', { mode });
  showModeIntersections();
  redrawOverview();
  const list = intersections();
  const id = list.some((i) => i.id === store.selectedId) ? store.selectedId : list[0] && list[0].id;
  if (id) await selectIntersection(id, { force: true });
}

function applySimStatus(status) {
  state.simStatus = status;
  if (state.sim) state.sim.apply(status);
  if (state.scene && store.mode === 'simulation') state.scene.setFrozen(isFrozen());
}

// --------------------------------------------------------------- socket

function connectSocket() {
  dash.setConnection('connecting');
  const socket = io({ transports: ['websocket', 'polling'] });
  state.socket = socket;

  socket.on('connect', () => {
    state.connected = true;
    dash.setConnection('connected', socket.io.engine.transport.name);
    // Every connection starts in the live room; rejoin the simulation room if needed.
    if (store.mode !== 'live') socket.emit('subscribe', { mode: store.mode });
    // Re-sync the selected intersection's event history after a reconnect.
    if (store.selectedId) selectIntersection(store.selectedId);
  });
  socket.on('disconnect', () => {
    state.connected = false;
    dash.setConnection('disconnected');
    renderSelected();
  });
  socket.io.on('reconnect_attempt', () => dash.setConnection('connecting'));

  socket.on('init', onInit);
  socket.on('trafficUpdate', onSnapshot);
  socket.on('signalUpdate', onSnapshot);
  socket.on('systemEvent', (evt) => {
    if (store.isCurrentEvent(evt)) dash.appendEvent(evt);
  });
  socket.on('simulationStatus', applySimStatus);
  socket.on('simulationReset', (payload) => {
    onInit(payload);
    if (store.mode === 'simulation' && store.selectedId) selectIntersection(store.selectedId, { force: true });
  });
  socket.on('subscribeError', (err) => console.warn('Socket subscription refused:', err && err.error));
}

// ----------------------------------------------------------------- boot

async function loadLists() {
  for (let attempt = 0; ; attempt += 1) {
    try {
      const [live, simulation] = await Promise.all([
        fetchJson('/api/intersections'),
        fetchJson('/api/simulation/intersections'),
      ]);
      state.lists = { live: live.intersections, simulation: simulation.intersections };
      if (state.lists.live.length) return;
    } catch (err) {
      dash.setConnection('disconnected');
    }
    await new Promise((r) => setTimeout(r, Math.min(5000, 1000 * (attempt + 1))));
  }
}

async function boot() {
  initializeLiveAI();
  dash.initLayout();
  dash.tickClock();
  dash.setDataState('offline', null);
  document.querySelectorAll('.mode-btn').forEach((btn) => {
    btn.addEventListener('click', () => setMode(btn.dataset.mode));
  });

  const scenePromise = createScene();
  await loadLists();

  const list = intersections();
  dash.renderIntersectionList(list, selectIntersection);
  state.map = new NetworkMap(document.getElementById('map'), list, (id) => selectIntersection(id));
  state.scene = await scenePromise;
  // Console diagnostics, e.g. trafficScene.stats()
  if (state.scene) window.trafficScene = state.scene;
  state.sim = new SimControls(() => store.selectedId, applySimStatus);
  applyModeChrome();

  const fromHash = decodeURIComponent(window.location.hash.slice(1));
  const initial = list.some((i) => i.id === fromHash) ? fromHash : list[0].id;

  connectSocket();
  await selectIntersection(initial);

  setInterval(() => {
    dash.tickClock();
    const snap = store.get();
    dash.tickCountdown(snap, isFrozen() || !state.connected);
    dash.tickDataAge(dataStateOf(snap), snap);
  }, 200);
}

window.addEventListener('hashchange', () => {
  const id = decodeURIComponent(window.location.hash.slice(1));
  if (id && id !== store.selectedId) selectIntersection(id, { pan: true });
});

boot();
