/**
 * Client-side state per data mode (no DOM, unit-tested).
 *
 *   live        real perception data       socket room "live",        REST /api
 *   simulation  generated by the simulator socket room "simulation",  REST /api/simulation
 *
 * Each mode keeps its own snapshots; switching modes never copies or merges
 * them. A payload is filed under the mode it declares (`dataMode`); a payload
 * without one is treated as live, never as simulation. Only payloads of the
 * active mode are reported as renderable, so simulated data can never be
 * drawn while the live view is shown (or the other way round).
 */
export const MODES = ['live', 'simulation'];

const modeOf = (payload) => (payload && payload.dataMode === 'simulation' ? 'simulation' : 'live');

export function createModeStore(initialMode = 'live') {
  if (!MODES.includes(initialMode)) throw new Error(`Unknown mode "${initialMode}"`);
  const snapshots = { live: new Map(), simulation: new Map() };
  let mode = initialMode;
  let selectedId = null;

  return {
    get mode() { return mode; },
    get selectedId() { return selectedId; },

    /** REST base path for the active mode. */
    apiBase() {
      return mode === 'simulation' ? '/api/simulation' : '/api';
    },

    /** Returns true when the mode actually changed. */
    switchMode(next) {
      if (!MODES.includes(next)) throw new Error(`Unknown mode "${next}"`);
      if (next === mode) return false;
      mode = next;
      return true;
    },

    /** Returns true when the selection changed. */
    select(id) {
      const changed = id !== selectedId;
      selectedId = id;
      return changed;
    },

    /** Files one snapshot under its own mode. Returns true if it belongs to the active mode. */
    accept(snapshot) {
      const m = modeOf(snapshot);
      snapshots[m].set(snapshot.intersectionId, snapshot);
      return m === mode;
    },

    /**
     * Replaces every snapshot of one mode (socket `init` / `simulationReset`).
     * Snapshots that declare a different mode are ignored. Returns true if
     * the replaced mode is the active one.
     */
    replaceAll(dataMode, list) {
      const m = modeOf({ dataMode });
      snapshots[m].clear();
      for (const snap of list) if (modeOf(snap) === m) snapshots[m].set(snap.intersectionId, snap);
      return m === mode;
    },

    /** True for a log event of the active mode and the selected intersection. */
    isCurrentEvent(event) {
      return modeOf(event) === mode && event.intersectionId === selectedId;
    },

    /** Snapshot of the active mode (selected intersection by default). */
    get(id = selectedId) {
      return snapshots[mode].get(id);
    },

    /** All snapshots of the active mode. */
    all() {
      return [...snapshots[mode].values()];
    },

    size(m) {
      return snapshots[m].size;
    },
  };
}
