const { Schema, model } = require('mongoose');
const {
  DIRECTIONS, EMERGENCY_TYPES, LIMITS, MODES, PHASES, VEHICLE_SIGNALS, PEDESTRIAN_SIGNALS, DATA_MODES, perDirection,
} = require('./constants');

/**
 * One accepted perception observation (POST /api/traffic), kept forever as
 * historical data. Append-only: records are never updated or expired.
 *
 * `traffic`, `pedestrians` and `emergency` are exactly what the producer
 * reported (after validation). `signal` is the controller state in effect
 * when the observation arrived, before the decision engine reacted to it.
 *
 * Stored as a MongoDB time-series collection (timeField `timestamp`,
 * metaField `intersectionId`): the feed arrives at about 1 Hz per
 * intersection, and time-series storage compresses that kind of data well.
 */

const approach = new Schema({
  vehicles: { type: Number, required: true, min: 0, max: LIMITS.vehicles },
  queueLength: { type: Number, required: true, min: 0, max: LIMITS.queueLength },
  waitingTime: { type: Number, required: true, min: 0, max: LIMITS.waitingTime }, // seconds
}, { _id: false });

const trafficRecordSchema = new Schema({
  intersectionId: { type: String, required: true, match: /^[A-Za-z0-9_-]{1,64}$/ },
  // 'live' = real perception data; 'simulation' = generated by the dashboard
  // simulator. Set by the server, never taken from the request. Always query
  // through modeFilter() (models/constants.js).
  dataMode: { type: String, enum: DATA_MODES, default: 'live', required: true },
  // Producer capture time; server receive time when the producer sent none.
  timestamp: { type: Date, required: true },
  receivedAt: { type: Date, required: true },
  // Producer tag ("mock" = simulated data). Filter on it before training.
  source: { type: String, default: null, maxlength: 32 },

  traffic: perDirection(() => ({ type: approach, required: true })),
  // true = people waiting to cross that leg (the feed has no pedestrian counts).
  pedestrians: perDirection(() => ({ type: Boolean, required: true })),
  emergency: {
    detected: { type: Boolean, required: true },
    type: { type: String, enum: EMERGENCY_TYPES, default: null },
    direction: { type: String, enum: DIRECTIONS, default: null },
    confidence: { type: Number, required: true, min: 0, max: 1 },
  },

  signal: {
    mode: { type: String, enum: MODES, required: true },
    phase: { type: String, enum: PHASES, required: true },
    signals: perDirection(() => ({ type: String, enum: VEHICLE_SIGNALS, required: true })),
    pedestrianSignals: perDirection(() => ({ type: String, enum: PEDESTRIAN_SIGNALS, required: true })),
  },
}, {
  collection: 'trafficRecords',
  versionKey: false,
  timeseries: { timeField: 'timestamp', metaField: 'intersectionId', granularity: 'seconds' },
});

// One intersection over a time range - the main history / export query.
trafficRecordSchema.index({ intersectionId: 1, timestamp: 1 });
// Every intersection over a time range (network-wide exports).
trafficRecordSchema.index({ timestamp: 1 });

module.exports = model('TrafficRecord', trafficRecordSchema);
